name: market_app
description: "A new Flutter project about a maketplace."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.6.0
  drift: ^2.15.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_secure_storage: ^9.0.0
  cryptography: ^2.7.0
  sqlite3_flutter_libs: ^0.5.24
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  drift_dev: ^2.15.0

flutter:
  uses-material-design: true

